# Datos de conexión a tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/creacionpj
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Spring JPA)
# 'update' crearía las tablas automáticamente si no existen o añadiría columnas nuevas
# Pero durante esta fase de Testing se utilizará create-drop
spring.jpa.hibernate.ddl-auto=create-drop

# Muestra en la consola de VS Code el SQL real que genera Spring (útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

##Mensajes de Logger
logging.level.root=INFO
logging.level.com.creacionpj=DEBUG