package com.creacionpj.model;

public enum TipoHabilidad {
    ACROBACIAS, ARTESANIA, ARCANO, ATLETISMO,
    DIPLOMACIA, ENGANO, INTERPRETACION, INTIMIDACION,
    LATROCINIO, MEDICINA, NATURALEZA, OCULTISMO, RELIGION,
    SABER, SIGILO, SOCIEDAD, SUPERVIVENCIA
}
