package com.creacionpj.model;

public enum TipoEquipo {
    ARMA, ARMADURA, AVENTURERO, ALQUIMICO, COMPANION, BANNER, INCIENSO, CONSUMIBLE, MATERIAL, RUNA, ESCUDO, LAZO,
    BASTON, TATUAJE, VARITA, INVESTIDO
}
