package com.creacionpj.model;

public enum TipoSubraza {
    ELFO_BOSQUE, ELFO_ARTICO, ELFO_CAVERNAS,ELFO_SUSURROS,ELFO_SILVANO,ELFO_VIDENTE,
    ENANO_FORJA, ENANO_ROCA, ENANO_ANTIGUA, ENANO_FUERTE,ENANO_MUERTE,
    GNOMO_CAMALEON,GNOMO_MANANTIAL,GNOMO_SENSIBLE,GNOMO_SOMBRIO,GNOMO_HADAS,
    GOBLIN_NIEVE, GOBLIN_DIENTES, GOBLIN_IRROMPIBLE, GOBLIN_IGNIFUGA, GOBLIN_TRIPAS,
    HUMANO_ELFO, HUMANO_ORCO, HUMANO_HABIL, HUMANO_VERSATIL,
    MEDIANO_AGALLAS, MEDIANO_COLINAS, MEDIANO_FLORESTAS, MEDIANO_CREPUSCULO, MEDIANO_NOMADA
}
