package com.creacionpj.model;

public enum TipoCompetenciaCombate {
    SINARMADURA, ARMADURALIGERA, ARMADURAMEDIA, ARMADURAPESADA, FORTALEZA, REFLEJOS, VOLUNTAD, SINARMAS,
    ARMASSIMPLES,ARMASMARCIALES, ARMASAVANZADAS, PERCEPCION,CLASE,CONJURO
}
